# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d2a51621989b8e20a9b018aafecfc7328a7df1d0e04ab67b2c9d66ece1c54b81ebe03aadc174340a56b88daeff359d8669b4f95e53d58ac26d07a733438bb01

test:
  secret_key_base: 0ecde27468744ae300ccc35ec9cf0a708dbd2d9880b0fee36b47011bf8e856da3d5c309f85ce57ded65fe1d20855fc0f3d6844cbad0e2065b454195e46ca7533

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
